#!/bin/bash
# Bundle: monday (Content Analyst, Weekly/CEO Brief, Content Strategist, Script Writer)
# Auto-generated by setup-bba-org.py

# Content Analyst
curl -sf -X POST "http://127.0.0.1:3100/api/routine-triggers/public/78c72a52a4f04195c3f5b0ad/fire" \
  -H "Authorization: Bearer e13106ec5f20b951f1c76e7717e74024dbd819268d11935c" \
  -H "Content-Type: application/json" -d '{}' &

# Weekly/CEO Brief
curl -sf -X POST "http://127.0.0.1:3100/api/routine-triggers/public/c88ce672a367bc25689e1544/fire" \
  -H "Authorization: Bearer 49f2d4f8fe983f93cb4677923889490805a7bb5d156095f2" \
  -H "Content-Type: application/json" -d '{}' &

# Content Strategist
curl -sf -X POST "http://127.0.0.1:3100/api/routine-triggers/public/99567b99b19de774fae0e0f4/fire" \
  -H "Authorization: Bearer 632066ad1f331e87cc52763aabbf5e994ad2bb95602cff59" \
  -H "Content-Type: application/json" -d '{}' &

# Script Writer
curl -sf -X POST "http://127.0.0.1:3100/api/routine-triggers/public/40bff39d8e2b620216a67565/fire" \
  -H "Authorization: Bearer e88ef2d9ca3deac064ba8bd9e92c9df79ccfec19babe84d8" \
  -H "Content-Type: application/json" -d '{}' &

wait
