#!/bin/bash
# Bundle: monday (Content Analyst, Weekly/CEO Brief, Content Strategist)
# Auto-generated by setup-bba-org.py

# Content Analyst
curl -sf -X POST "http://127.0.0.1:3100/api/routine-triggers/public/a02b4ff6e53f03320f17e6de/fire" \
  -H "Authorization: Bearer 67b97c371bced8bc822dd7ddbbe2114e2693210fb56b4235" \
  -H "Content-Type: application/json" -d '{}' &

# Weekly/CEO Brief
curl -sf -X POST "http://127.0.0.1:3100/api/routine-triggers/public/c88ce672a367bc25689e1544/fire" \
  -H "Authorization: Bearer 49f2d4f8fe983f93cb4677923889490805a7bb5d156095f2" \
  -H "Content-Type: application/json" -d '{}' &

# Content Strategist
curl -sf -X POST "http://127.0.0.1:3100/api/routine-triggers/public/99567b99b19de774fae0e0f4/fire" \
  -H "Authorization: Bearer 632066ad1f331e87cc52763aabbf5e994ad2bb95602cff59" \
  -H "Content-Type: application/json" -d '{}' &

wait
